-- MySQL Script generated by MySQL Workbench
-- Mon Jan 21 12:15:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema center_sport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema center_sport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `center_sport` DEFAULT CHARACTER SET utf8mb4 ;
USE `center_sport` ;

-- -----------------------------------------------------
-- Table `center_sport`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `center_sport`.`utilisateurs` (
  `id_utilisateur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_utilisateur` VARCHAR(45) NOT NULL,
  `prenom_utilisateur` VARCHAR(45) NOT NULL,
  `courriel_utilisateur` VARCHAR(45) NOT NULL,
  `mot_de_pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `center_sport`.`gestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `center_sport`.`gestions` (
  `idgestions` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `courriel` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgestions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `center_sport`.`activites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `center_sport`.`activites` (
  `id_activite` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_activite` VARCHAR(45) NOT NULL,
  `categorie_activite` VARCHAR(45) NOT NULL,
  `nombre_place_activite` INT UNSIGNED NOT NULL,
  `gestions_idgestions` INT NOT NULL,
  PRIMARY KEY (`id_activite`, `gestions_idgestions`),
  INDEX `fk_activites_gestions1_idx` (`gestions_idgestions` ASC) ,
  CONSTRAINT `fk_activites_gestions1`
    FOREIGN KEY (`gestions_idgestions`)
    REFERENCES `center_sport`.`gestions` (`idgestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `center_sport`.`inscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `center_sport`.`inscriptions` (
  `id_inscription` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `utilisateurs_id_utilisateur` INT UNSIGNED NOT NULL,
  `activites_id_activite` INT UNSIGNED NOT NULL,
  `date_paiement_inscription` DATE NULL,
  `statut_inscription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_inscription`),
  INDEX `fk_utilisateurs_has_activites_activites1_idx` (`activites_id_activite` ASC) ,
  INDEX `fk_utilisateurs_has_activites_utilisateurs1_idx` (`utilisateurs_id_utilisateur` ASC) ,
  CONSTRAINT `fk_utilisateurs_has_activites_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id_utilisateur`)
    REFERENCES `center_sport`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_has_activites_activites1`
    FOREIGN KEY (`activites_id_activite`)
    REFERENCES `center_sport`.`activites` (`id_activite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
